//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSession
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="UserSession.zaygbcsys_ws_userses")]
    public interface zaygbcsys_ws_userses
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:zaygbcsys_ws_userses:ZaygbcsysRf" +
            "csUsersesRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserSession.ZaygbcsysRfcsUsersesResponse1> ZaygbcsysRfcsUsersesAsync(UserSession.ZaygbcsysRfcsUsersesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsUserses
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbssysUsersessRf
    {
        
        private string sessionTypeField;
        
        private string extStypeField;
        
        private string extStateField;
        
        private string extTimeField;
        
        private string extTraceField;
        
        private string lineColField;
        
        private string ipaddrField;
        
        private string selectedField;
        
        private int totalMemKbField;
        
        private int totalMemBruttoKbField;
        
        private int totalMemHeapKbField;
        
        private int totalMemHyperKbField;
        
        private int totalMemAbapKbField;
        
        private string applInfoField;
        
        private string actProgramField;
        
        private string securityContextField;
        
        private int logonHdlField;
        
        private int logonIdField;
        
        private int sessionHdlField;
        
        private string sessionKeyField;
        
        private string tenantField;
        
        private string userNameField;
        
        private string applicationField;
        
        private string locationInfoField;
        
        private int sessionsField;
        
        private string rfcHdlField;
        
        private string rfcTypeLongField;
        
        private string serverNameField;
        
        private byte traceField;
        
        private string logonPrivilegeField;
        
        private string priorityField;
        
        private int openTasksField;
        
        private string websocketHandleField;
        
        private string sapGuiVersionField;
        
        private int pagingBlocksField;
        
        private int requestTimeField;
        
        private string stateField;
        
        private string clientIpAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SessionType
        {
            get
            {
                return this.sessionTypeField;
            }
            set
            {
                this.sessionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ExtStype
        {
            get
            {
                return this.extStypeField;
            }
            set
            {
                this.extStypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ExtState
        {
            get
            {
                return this.extStateField;
            }
            set
            {
                this.extStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ExtTime
        {
            get
            {
                return this.extTimeField;
            }
            set
            {
                this.extTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ExtTrace
        {
            get
            {
                return this.extTraceField;
            }
            set
            {
                this.extTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LineCol
        {
            get
            {
                return this.lineColField;
            }
            set
            {
                this.lineColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Ipaddr
        {
            get
            {
                return this.ipaddrField;
            }
            set
            {
                this.ipaddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Selected
        {
            get
            {
                return this.selectedField;
            }
            set
            {
                this.selectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int TotalMemKb
        {
            get
            {
                return this.totalMemKbField;
            }
            set
            {
                this.totalMemKbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int TotalMemBruttoKb
        {
            get
            {
                return this.totalMemBruttoKbField;
            }
            set
            {
                this.totalMemBruttoKbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int TotalMemHeapKb
        {
            get
            {
                return this.totalMemHeapKbField;
            }
            set
            {
                this.totalMemHeapKbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int TotalMemHyperKb
        {
            get
            {
                return this.totalMemHyperKbField;
            }
            set
            {
                this.totalMemHyperKbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int TotalMemAbapKb
        {
            get
            {
                return this.totalMemAbapKbField;
            }
            set
            {
                this.totalMemAbapKbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ApplInfo
        {
            get
            {
                return this.applInfoField;
            }
            set
            {
                this.applInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ActProgram
        {
            get
            {
                return this.actProgramField;
            }
            set
            {
                this.actProgramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string SecurityContext
        {
            get
            {
                return this.securityContextField;
            }
            set
            {
                this.securityContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int LogonHdl
        {
            get
            {
                return this.logonHdlField;
            }
            set
            {
                this.logonHdlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int LogonId
        {
            get
            {
                return this.logonIdField;
            }
            set
            {
                this.logonIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int SessionHdl
        {
            get
            {
                return this.sessionHdlField;
            }
            set
            {
                this.sessionHdlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SessionKey
        {
            get
            {
                return this.sessionKeyField;
            }
            set
            {
                this.sessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Tenant
        {
            get
            {
                return this.tenantField;
            }
            set
            {
                this.tenantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string LocationInfo
        {
            get
            {
                return this.locationInfoField;
            }
            set
            {
                this.locationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int Sessions
        {
            get
            {
                return this.sessionsField;
            }
            set
            {
                this.sessionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string RfcHdl
        {
            get
            {
                return this.rfcHdlField;
            }
            set
            {
                this.rfcHdlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string RfcTypeLong
        {
            get
            {
                return this.rfcTypeLongField;
            }
            set
            {
                this.rfcTypeLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ServerName
        {
            get
            {
                return this.serverNameField;
            }
            set
            {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public byte Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string LogonPrivilege
        {
            get
            {
                return this.logonPrivilegeField;
            }
            set
            {
                this.logonPrivilegeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public int OpenTasks
        {
            get
            {
                return this.openTasksField;
            }
            set
            {
                this.openTasksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string WebsocketHandle
        {
            get
            {
                return this.websocketHandleField;
            }
            set
            {
                this.websocketHandleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string SapGuiVersion
        {
            get
            {
                return this.sapGuiVersionField;
            }
            set
            {
                this.sapGuiVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public int PagingBlocks
        {
            get
            {
                return this.pagingBlocksField;
            }
            set
            {
                this.pagingBlocksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public int RequestTime
        {
            get
            {
                return this.requestTimeField;
            }
            set
            {
                this.requestTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string ClientIpAddr
        {
            get
            {
                return this.clientIpAddrField;
            }
            set
            {
                this.clientIpAddrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsUsersesResponse
    {
        
        private string efErrMessageField;
        
        private ZaygbssysUsersessRf[] etUsrSessListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string EfErrMessage
        {
            get
            {
                return this.efErrMessageField;
            }
            set
            {
                this.efErrMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZaygbssysUsersessRf[] EtUsrSessList
        {
            get
            {
                return this.etUsrSessListField;
            }
            set
            {
                this.etUsrSessListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsUsersesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public UserSession.ZaygbcsysRfcsUserses ZaygbcsysRfcsUserses;
        
        public ZaygbcsysRfcsUsersesRequest()
        {
        }
        
        public ZaygbcsysRfcsUsersesRequest(UserSession.ZaygbcsysRfcsUserses ZaygbcsysRfcsUserses)
        {
            this.ZaygbcsysRfcsUserses = ZaygbcsysRfcsUserses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsUsersesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public UserSession.ZaygbcsysRfcsUsersesResponse ZaygbcsysRfcsUsersesResponse;
        
        public ZaygbcsysRfcsUsersesResponse1()
        {
        }
        
        public ZaygbcsysRfcsUsersesResponse1(UserSession.ZaygbcsysRfcsUsersesResponse ZaygbcsysRfcsUsersesResponse)
        {
            this.ZaygbcsysRfcsUsersesResponse = ZaygbcsysRfcsUsersesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface zaygbcsys_ws_usersesChannel : UserSession.zaygbcsys_ws_userses, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class zaygbcsys_ws_usersesClient : System.ServiceModel.ClientBase<UserSession.zaygbcsys_ws_userses>, UserSession.zaygbcsys_ws_userses
    {
        
        public zaygbcsys_ws_usersesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UserSession.ZaygbcsysRfcsUsersesResponse1> UserSession.zaygbcsys_ws_userses.ZaygbcsysRfcsUsersesAsync(UserSession.ZaygbcsysRfcsUsersesRequest request)
        {
            return base.Channel.ZaygbcsysRfcsUsersesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UserSession.ZaygbcsysRfcsUsersesResponse1> ZaygbcsysRfcsUsersesAsync(UserSession.ZaygbcsysRfcsUserses ZaygbcsysRfcsUserses)
        {
            UserSession.ZaygbcsysRfcsUsersesRequest inValue = new UserSession.ZaygbcsysRfcsUsersesRequest();
            inValue.ZaygbcsysRfcsUserses = ZaygbcsysRfcsUserses;
            return ((UserSession.zaygbcsys_ws_userses)(this)).ZaygbcsysRfcsUsersesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
