//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackgroundProcess
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="BackgroundProcess.zaygbcsys_ws_bckgprc")]
    public interface zaygbcsys_ws_bckgprc
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:zaygbcsys_ws_bckgprc:ZaygbcsysRf" +
            "csBckgprcRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BackgroundProcess.ZaygbcsysRfcsBckgprcResponse1> ZaygbcsysRfcsBckgprcAsync(BackgroundProcess.ZaygbcsysRfcsBckgprcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsBckgprc
    {
        
        private Btcselect isJobselParamsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Btcselect IsJobselParams
        {
            get
            {
                return this.isJobselParamsField;
            }
            set
            {
                this.isJobselParamsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Btcselect
    {
        
        private string jobnameField;
        
        private string jobcountField;
        
        private string jobgroupField;
        
        private string usernameField;
        
        private string fromDateField;
        
        private System.DateTime fromTimeField;
        
        private string toDateField;
        
        private System.DateTime toTimeField;
        
        private string noDateField;
        
        private string withPredField;
        
        private string eventidField;
        
        private string eventparmField;
        
        private string prelimField;
        
        private string schedulField;
        
        private string readyField;
        
        private string runningField;
        
        private string finishedField;
        
        private string abortedField;
        
        private string abapnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Jobname
        {
            get
            {
                return this.jobnameField;
            }
            set
            {
                this.jobnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Jobcount
        {
            get
            {
                return this.jobcountField;
            }
            set
            {
                this.jobcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Jobgroup
        {
            get
            {
                return this.jobgroupField;
            }
            set
            {
                this.jobgroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=5)]
        public System.DateTime FromTime
        {
            get
            {
                return this.fromTimeField;
            }
            set
            {
                this.fromTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ToDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=7)]
        public System.DateTime ToTime
        {
            get
            {
                return this.toTimeField;
            }
            set
            {
                this.toTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NoDate
        {
            get
            {
                return this.noDateField;
            }
            set
            {
                this.noDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string WithPred
        {
            get
            {
                return this.withPredField;
            }
            set
            {
                this.withPredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Eventid
        {
            get
            {
                return this.eventidField;
            }
            set
            {
                this.eventidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Eventparm
        {
            get
            {
                return this.eventparmField;
            }
            set
            {
                this.eventparmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Prelim
        {
            get
            {
                return this.prelimField;
            }
            set
            {
                this.prelimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Schedul
        {
            get
            {
                return this.schedulField;
            }
            set
            {
                this.schedulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Ready
        {
            get
            {
                return this.readyField;
            }
            set
            {
                this.readyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Running
        {
            get
            {
                return this.runningField;
            }
            set
            {
                this.runningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Finished
        {
            get
            {
                return this.finishedField;
            }
            set
            {
                this.finishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Aborted
        {
            get
            {
                return this.abortedField;
            }
            set
            {
                this.abortedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Abapname
        {
            get
            {
                return this.abapnameField;
            }
            set
            {
                this.abapnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbssysTbtcjobBkRf
    {
        
        private string jobnameField;
        
        private string jobcountField;
        
        private string jobgroupField;
        
        private string intreportField;
        
        private int stepcountField;
        
        private string sdlstrtdtField;
        
        private System.DateTime sdlstrttmField;
        
        private string btcsystemField;
        
        private string sdldateField;
        
        private System.DateTime sdltimeField;
        
        private string sdlunameField;
        
        private string lastchdateField;
        
        private System.DateTime lastchtimeField;
        
        private string lastchnameField;
        
        private string reldateField;
        
        private System.DateTime reltimeField;
        
        private string relunameField;
        
        private string strtdateField;
        
        private System.DateTime strttimeField;
        
        private string enddateField;
        
        private System.DateTime endtimeField;
        
        private string prdminsField;
        
        private string prdhoursField;
        
        private string prddaysField;
        
        private string prdweeksField;
        
        private string prdmonthsField;
        
        private string periodicField;
        
        private string delanfrepField;
        
        private string emergmodeField;
        
        private string statusField;
        
        private string newflagField;
        
        private string authcknamField;
        
        private string authckmanField;
        
        private int succnumField;
        
        private int prednumField;
        
        private string joblogField;
        
        private string laststrtdtField;
        
        private System.DateTime laststrttmField;
        
        private int wpnumberField;
        
        private int wpprocidField;
        
        private string eventidField;
        
        private string eventparmField;
        
        private string btcsysreaxField;
        
        private string jobclassField;
        
        private int priorityField;
        
        private string eventcountField;
        
        private string checkstatField;
        
        private string calendaridField;
        
        private string prdbehavField;
        
        private string execserverField;
        
        private int eomcorrectField;
        
        private int calcorrectField;
        
        private string reaxserverField;
        
        private string reclogsysField;
        
        private string recobjtypeField;
        
        private string recobjkeyField;
        
        private string recdescribField;
        
        private string tgtsrvgrpField;
        
        private string prognameField;
        
        private string xpgprogField;
        
        private string extcmdField;
        
        private int durationField;
        
        private int latencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Jobname
        {
            get
            {
                return this.jobnameField;
            }
            set
            {
                this.jobnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Jobcount
        {
            get
            {
                return this.jobcountField;
            }
            set
            {
                this.jobcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Jobgroup
        {
            get
            {
                return this.jobgroupField;
            }
            set
            {
                this.jobgroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Intreport
        {
            get
            {
                return this.intreportField;
            }
            set
            {
                this.intreportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int Stepcount
        {
            get
            {
                return this.stepcountField;
            }
            set
            {
                this.stepcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sdlstrtdt
        {
            get
            {
                return this.sdlstrtdtField;
            }
            set
            {
                this.sdlstrtdtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=6)]
        public System.DateTime Sdlstrttm
        {
            get
            {
                return this.sdlstrttmField;
            }
            set
            {
                this.sdlstrttmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Btcsystem
        {
            get
            {
                return this.btcsystemField;
            }
            set
            {
                this.btcsystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Sdldate
        {
            get
            {
                return this.sdldateField;
            }
            set
            {
                this.sdldateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=9)]
        public System.DateTime Sdltime
        {
            get
            {
                return this.sdltimeField;
            }
            set
            {
                this.sdltimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Sdluname
        {
            get
            {
                return this.sdlunameField;
            }
            set
            {
                this.sdlunameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Lastchdate
        {
            get
            {
                return this.lastchdateField;
            }
            set
            {
                this.lastchdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=12)]
        public System.DateTime Lastchtime
        {
            get
            {
                return this.lastchtimeField;
            }
            set
            {
                this.lastchtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Lastchname
        {
            get
            {
                return this.lastchnameField;
            }
            set
            {
                this.lastchnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Reldate
        {
            get
            {
                return this.reldateField;
            }
            set
            {
                this.reldateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=15)]
        public System.DateTime Reltime
        {
            get
            {
                return this.reltimeField;
            }
            set
            {
                this.reltimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Reluname
        {
            get
            {
                return this.relunameField;
            }
            set
            {
                this.relunameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Strtdate
        {
            get
            {
                return this.strtdateField;
            }
            set
            {
                this.strtdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=18)]
        public System.DateTime Strttime
        {
            get
            {
                return this.strttimeField;
            }
            set
            {
                this.strttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=20)]
        public System.DateTime Endtime
        {
            get
            {
                return this.endtimeField;
            }
            set
            {
                this.endtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Prdmins
        {
            get
            {
                return this.prdminsField;
            }
            set
            {
                this.prdminsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Prdhours
        {
            get
            {
                return this.prdhoursField;
            }
            set
            {
                this.prdhoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Prddays
        {
            get
            {
                return this.prddaysField;
            }
            set
            {
                this.prddaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Prdweeks
        {
            get
            {
                return this.prdweeksField;
            }
            set
            {
                this.prdweeksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Prdmonths
        {
            get
            {
                return this.prdmonthsField;
            }
            set
            {
                this.prdmonthsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Periodic
        {
            get
            {
                return this.periodicField;
            }
            set
            {
                this.periodicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Delanfrep
        {
            get
            {
                return this.delanfrepField;
            }
            set
            {
                this.delanfrepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Emergmode
        {
            get
            {
                return this.emergmodeField;
            }
            set
            {
                this.emergmodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Newflag
        {
            get
            {
                return this.newflagField;
            }
            set
            {
                this.newflagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Authcknam
        {
            get
            {
                return this.authcknamField;
            }
            set
            {
                this.authcknamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Authckman
        {
            get
            {
                return this.authckmanField;
            }
            set
            {
                this.authckmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public int Succnum
        {
            get
            {
                return this.succnumField;
            }
            set
            {
                this.succnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public int Prednum
        {
            get
            {
                return this.prednumField;
            }
            set
            {
                this.prednumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Joblog
        {
            get
            {
                return this.joblogField;
            }
            set
            {
                this.joblogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Laststrtdt
        {
            get
            {
                return this.laststrtdtField;
            }
            set
            {
                this.laststrtdtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=37)]
        public System.DateTime Laststrttm
        {
            get
            {
                return this.laststrttmField;
            }
            set
            {
                this.laststrttmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public int Wpnumber
        {
            get
            {
                return this.wpnumberField;
            }
            set
            {
                this.wpnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public int Wpprocid
        {
            get
            {
                return this.wpprocidField;
            }
            set
            {
                this.wpprocidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string Eventid
        {
            get
            {
                return this.eventidField;
            }
            set
            {
                this.eventidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string Eventparm
        {
            get
            {
                return this.eventparmField;
            }
            set
            {
                this.eventparmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string Btcsysreax
        {
            get
            {
                return this.btcsysreaxField;
            }
            set
            {
                this.btcsysreaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string Jobclass
        {
            get
            {
                return this.jobclassField;
            }
            set
            {
                this.jobclassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string Eventcount
        {
            get
            {
                return this.eventcountField;
            }
            set
            {
                this.eventcountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string Checkstat
        {
            get
            {
                return this.checkstatField;
            }
            set
            {
                this.checkstatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string Calendarid
        {
            get
            {
                return this.calendaridField;
            }
            set
            {
                this.calendaridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string Prdbehav
        {
            get
            {
                return this.prdbehavField;
            }
            set
            {
                this.prdbehavField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string Execserver
        {
            get
            {
                return this.execserverField;
            }
            set
            {
                this.execserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public int Eomcorrect
        {
            get
            {
                return this.eomcorrectField;
            }
            set
            {
                this.eomcorrectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public int Calcorrect
        {
            get
            {
                return this.calcorrectField;
            }
            set
            {
                this.calcorrectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string Reaxserver
        {
            get
            {
                return this.reaxserverField;
            }
            set
            {
                this.reaxserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string Reclogsys
        {
            get
            {
                return this.reclogsysField;
            }
            set
            {
                this.reclogsysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string Recobjtype
        {
            get
            {
                return this.recobjtypeField;
            }
            set
            {
                this.recobjtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string Recobjkey
        {
            get
            {
                return this.recobjkeyField;
            }
            set
            {
                this.recobjkeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string Recdescrib
        {
            get
            {
                return this.recdescribField;
            }
            set
            {
                this.recdescribField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string Tgtsrvgrp
        {
            get
            {
                return this.tgtsrvgrpField;
            }
            set
            {
                this.tgtsrvgrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string Progname
        {
            get
            {
                return this.prognameField;
            }
            set
            {
                this.prognameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string Xpgprog
        {
            get
            {
                return this.xpgprogField;
            }
            set
            {
                this.xpgprogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string Extcmd
        {
            get
            {
                return this.extcmdField;
            }
            set
            {
                this.extcmdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public int Latency
        {
            get
            {
                return this.latencyField;
            }
            set
            {
                this.latencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsBckgprcResponse
    {
        
        private ZaygbssysTbtcjobBkRf[] etJoblistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZaygbssysTbtcjobBkRf[] EtJoblist
        {
            get
            {
                return this.etJoblistField;
            }
            set
            {
                this.etJoblistField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsBckgprcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public BackgroundProcess.ZaygbcsysRfcsBckgprc ZaygbcsysRfcsBckgprc;
        
        public ZaygbcsysRfcsBckgprcRequest()
        {
        }
        
        public ZaygbcsysRfcsBckgprcRequest(BackgroundProcess.ZaygbcsysRfcsBckgprc ZaygbcsysRfcsBckgprc)
        {
            this.ZaygbcsysRfcsBckgprc = ZaygbcsysRfcsBckgprc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsBckgprcResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public BackgroundProcess.ZaygbcsysRfcsBckgprcResponse ZaygbcsysRfcsBckgprcResponse;
        
        public ZaygbcsysRfcsBckgprcResponse1()
        {
        }
        
        public ZaygbcsysRfcsBckgprcResponse1(BackgroundProcess.ZaygbcsysRfcsBckgprcResponse ZaygbcsysRfcsBckgprcResponse)
        {
            this.ZaygbcsysRfcsBckgprcResponse = ZaygbcsysRfcsBckgprcResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface zaygbcsys_ws_bckgprcChannel : BackgroundProcess.zaygbcsys_ws_bckgprc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class zaygbcsys_ws_bckgprcClient : System.ServiceModel.ClientBase<BackgroundProcess.zaygbcsys_ws_bckgprc>, BackgroundProcess.zaygbcsys_ws_bckgprc
    {
        
        public zaygbcsys_ws_bckgprcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BackgroundProcess.ZaygbcsysRfcsBckgprcResponse1> BackgroundProcess.zaygbcsys_ws_bckgprc.ZaygbcsysRfcsBckgprcAsync(BackgroundProcess.ZaygbcsysRfcsBckgprcRequest request)
        {
            return base.Channel.ZaygbcsysRfcsBckgprcAsync(request);
        }
        
        public System.Threading.Tasks.Task<BackgroundProcess.ZaygbcsysRfcsBckgprcResponse1> ZaygbcsysRfcsBckgprcAsync(BackgroundProcess.ZaygbcsysRfcsBckgprc ZaygbcsysRfcsBckgprc)
        {
            BackgroundProcess.ZaygbcsysRfcsBckgprcRequest inValue = new BackgroundProcess.ZaygbcsysRfcsBckgprcRequest();
            inValue.ZaygbcsysRfcsBckgprc = ZaygbcsysRfcsBckgprc;
            return ((BackgroundProcess.zaygbcsys_ws_bckgprc)(this)).ZaygbcsysRfcsBckgprcAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
