//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckDumps
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="CheckDumps.zaygbcsys_ws_chkdumps")]
    public interface zaygbcsys_ws_chkdumps
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:zaygbcsys_ws_chkdumps:ZaygbcsysR" +
            "fcsChkdumpsRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CheckDumps.ZaygbcsysRfcsChkdumpsResponse1> ZaygbcsysRfcsChkdumpsAsync(CheckDumps.ZaygbcsysRfcsChkdumpsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsChkdumps
    {
        
        private string ifClientField;
        
        private string ifDatumFrField;
        
        private string ifDatumToField;
        
        private string ifErridField;
        
        private string ifExceptidField;
        
        private string ifPrgidField;
        
        private string ifTodayField;
        
        private string ifTrnidField;
        
        private string ifUnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IfClient
        {
            get
            {
                return this.ifClientField;
            }
            set
            {
                this.ifClientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IfDatumFr
        {
            get
            {
                return this.ifDatumFrField;
            }
            set
            {
                this.ifDatumFrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IfDatumTo
        {
            get
            {
                return this.ifDatumToField;
            }
            set
            {
                this.ifDatumToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IfErrid
        {
            get
            {
                return this.ifErridField;
            }
            set
            {
                this.ifErridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IfExceptid
        {
            get
            {
                return this.ifExceptidField;
            }
            set
            {
                this.ifExceptidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IfPrgid
        {
            get
            {
                return this.ifPrgidField;
            }
            set
            {
                this.ifPrgidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IfToday
        {
            get
            {
                return this.ifTodayField;
            }
            set
            {
                this.ifTodayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IfTrnid
        {
            get
            {
                return this.ifTrnidField;
            }
            set
            {
                this.ifTrnidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IfUname
        {
            get
            {
                return this.ifUnameField;
            }
            set
            {
                this.ifUnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Rdumpov
    {
        
        private string datumField;
        
        private System.DateTime uzeitField;
        
        private string ahostField;
        
        private string unameField;
        
        private string mandtField;
        
        private string xholdField;
        
        private string erroridField;
        
        private string rexceptionField;
        
        private string componentField;
        
        private string gprogramField;
        
        private int modnoField;
        
        private string tidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="time", Order=1)]
        public System.DateTime Uzeit
        {
            get
            {
                return this.uzeitField;
            }
            set
            {
                this.uzeitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ahost
        {
            get
            {
                return this.ahostField;
            }
            set
            {
                this.ahostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Uname
        {
            get
            {
                return this.unameField;
            }
            set
            {
                this.unameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Mandt
        {
            get
            {
                return this.mandtField;
            }
            set
            {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Xhold
        {
            get
            {
                return this.xholdField;
            }
            set
            {
                this.xholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Errorid
        {
            get
            {
                return this.erroridField;
            }
            set
            {
                this.erroridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Rexception
        {
            get
            {
                return this.rexceptionField;
            }
            set
            {
                this.rexceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Component
        {
            get
            {
                return this.componentField;
            }
            set
            {
                this.componentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Gprogram
        {
            get
            {
                return this.gprogramField;
            }
            set
            {
                this.gprogramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int Modno
        {
            get
            {
                return this.modnoField;
            }
            set
            {
                this.modnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Tid
        {
            get
            {
                return this.tidField;
            }
            set
            {
                this.tidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZaygbcsysRfcsChkdumpsResponse
    {
        
        private Rdumpov[] etDumplistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Rdumpov[] EtDumplist
        {
            get
            {
                return this.etDumplistField;
            }
            set
            {
                this.etDumplistField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsChkdumpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public CheckDumps.ZaygbcsysRfcsChkdumps ZaygbcsysRfcsChkdumps;
        
        public ZaygbcsysRfcsChkdumpsRequest()
        {
        }
        
        public ZaygbcsysRfcsChkdumpsRequest(CheckDumps.ZaygbcsysRfcsChkdumps ZaygbcsysRfcsChkdumps)
        {
            this.ZaygbcsysRfcsChkdumps = ZaygbcsysRfcsChkdumps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZaygbcsysRfcsChkdumpsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public CheckDumps.ZaygbcsysRfcsChkdumpsResponse ZaygbcsysRfcsChkdumpsResponse;
        
        public ZaygbcsysRfcsChkdumpsResponse1()
        {
        }
        
        public ZaygbcsysRfcsChkdumpsResponse1(CheckDumps.ZaygbcsysRfcsChkdumpsResponse ZaygbcsysRfcsChkdumpsResponse)
        {
            this.ZaygbcsysRfcsChkdumpsResponse = ZaygbcsysRfcsChkdumpsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface zaygbcsys_ws_chkdumpsChannel : CheckDumps.zaygbcsys_ws_chkdumps, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class zaygbcsys_ws_chkdumpsClient : System.ServiceModel.ClientBase<CheckDumps.zaygbcsys_ws_chkdumps>, CheckDumps.zaygbcsys_ws_chkdumps
    {
        
        public zaygbcsys_ws_chkdumpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CheckDumps.ZaygbcsysRfcsChkdumpsResponse1> CheckDumps.zaygbcsys_ws_chkdumps.ZaygbcsysRfcsChkdumpsAsync(CheckDumps.ZaygbcsysRfcsChkdumpsRequest request)
        {
            return base.Channel.ZaygbcsysRfcsChkdumpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CheckDumps.ZaygbcsysRfcsChkdumpsResponse1> ZaygbcsysRfcsChkdumpsAsync(CheckDumps.ZaygbcsysRfcsChkdumps ZaygbcsysRfcsChkdumps)
        {
            CheckDumps.ZaygbcsysRfcsChkdumpsRequest inValue = new CheckDumps.ZaygbcsysRfcsChkdumpsRequest();
            inValue.ZaygbcsysRfcsChkdumps = ZaygbcsysRfcsChkdumps;
            return ((CheckDumps.zaygbcsys_ws_chkdumps)(this)).ZaygbcsysRfcsChkdumpsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
